### ISSUE TITLE
Create a tracking system to detect the orientation of lips in the frame 

### ISSUE THREAD

**Issue by sagarvincent** [sagarvincent/SpeechReadingSystem#2]
In order to track the changes in lip orientation in each frame, it is important to describe the orientation of lips in each frame correctly

- [ ] assign enough feature points so as to accurately model lip orientation
- [ ] - If possible, try and classify each orientation into a preset categories.
- [ ] - The categories can be defined as , eg: closed, wide. When a person speaks, he always follows the same pattern with his lips. This  should be reflected in category selection such that, a word should be always formed by a sequence of categories, and the sequence should be different for each different pronounce
